### ISSUE TITLE
Loosing Z-Wave values

### ISSUE THREAD

**Issue by benoit934** [openhab/openhab#2201]
Hello, I've a Fibaro Motion sensor and one Danfoss Thermostat.

After a while all values, setpoint, etc. is lost, I need to manually wake up the device to get back those values.

I tried to set it as persistant but doesn't working, I've set The Fibaro to send the data regularly but what can I do for the Thermostat setup, I even want to save the battery

**Comment by cdjackson** [comment]
If you have a problem with persistence, then this isn't anything to do with the zwave binding since persistence is not part of the bindings.

Are other items being persisted ok?
When do the values disappear? I assume after startup?

**Comment by benoit934** [comment]
The demo data is saved, when I use HABmin I have group(rrd4j:everyMinute, rrd4j:restoreOnStartup)

But I don't have any graph, for demo stuff I have graph

**Comment by benoit934** [comment]
I've switched to DB4O with * : strategy = everyChange, everyDay, restoreOnStartup

Now it's working, but why RRD4J don't work, what is the better database ?? I can setup a MySQL server on my NAS to save many data if I can get a good enough perfs.

**Comment by cdjackson** [comment]
I use mysql - it works fine.

**Comment by cdjackson** [comment]
I suggest to close this as the problem is fixed (ie zwave value problem). If there's a problem with RRD4J then it's probably best to open a separate issue?

**Comment by benoit934** [comment]
I don't know if I still have an issue with RRD4J I let DB4O.

So I close this ticket because for others users it seem to work well.
