### ISSUE TITLE
Missing verification key for DEB package installation from bintray.com

### ISSUE THREAD

**Issue by nRaecheR** [openhab/openhab#2649]
I couldn't find the signing key for the Debian/Ubuntu packages of OpenHAB 1.7.0 from bintray.com. The installer tool "apt-get" is complaining about the missing verification when you try to install the packages, see here : 

```
sudo apt-get install openhab-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  openhab-runtime
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 36.8 MB of archives.
After this operation, 41.4 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openhab-runtime
Install these packages without verification? [y/N]
```

This makes automatic installs/updates impossible and makes it possible to do a Man in the Middle attack by modifiying the packages.

Could someone please provide the needed key ?

**Comment by teichsta** [comment]
@theoweiss could you help with this one? Thanks, Thomas E.-E.

**Comment by theoweiss** [comment]
@teichsta yes. Just back from vacation, give me some time.

**Comment by schinken** [comment]
Anything new about the verification key? Installing from packages without verification feels wrong. 
Would be nice to have one in the near future

**Comment by teichsta** [comment]
any news on this @theoweiss?

**Comment by theoweiss** [comment]
Here is a description what has to be done:
http://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/
I will try it first with my private repo and give you some feedback.

**Comment by teichsta** [comment]
fixed with #2965

**Comment by nRaecheR** [comment]
@teichsta Sorry, I tried it and it still won't work. Here the output from apt-get dist-upgrade *after* importing the GPG key from bintray mentioned in the wiki ( https://github.com/openhab/openhab/wiki/Linux---OS-X ): 

```
The following packages will be upgraded:
   openhab-addon-action-mail (1.7.0 => 1.7.1)
   openhab-addon-binding-zwave (1.7.0 => 1.7.1)
   openhab-runtime (1.7.0 => 1.7.1)
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 37.8 MB/37.9 MB of archives.
After this operation, 6144 B of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  openhab-runtime openhab-addon-action-mail openhab-addon-binding-zwave
Install these packages without verification? [y/N] y
Err http://dl.bintray.com/openhab/apt-repo/ stable/main openhab-runtime all 1.7.1
  403  Forbidden
Err http://dl.bintray.com/openhab/apt-repo/ stable/main openhab-addon-binding-zwave all 1.7.1
  403  Forbidden
E: Failed to fetch http://dl.bintray.com/openhab/apt-repo/pool/main/o/openhab-runtime-1.7.1.deb  403  Forbidden

E: Failed to fetch http://dl.bintray.com/openhab/apt-repo/pool/main/o/openhab-addon-binding-zwave-1.7.1.deb  403  Forbidden

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

Here's the installed keys : 

```
raecher@vm-smarthome:~$ sudo apt-key list
/etc/apt/trusted.gpg
--------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

pub   1024D/3E5C1192 2010-09-20
uid                  Ubuntu Extras Archive Automatic Signing Key <ftpmaster@ubuntu.com>

pub   4096R/A88CD092 2014-07-24
uid                  Arne Bockholdt (Signing key for internal apt repository) <vm-download@athena.bockholdt.com>
sub   4096R/88A24569 2014-07-24

pub   4096R/D401AB61 2015-02-17
uid                  Bintray (by JFrog) <bintray@bintray.com>
sub   4096R/DBE1D0A2 2015-02-17

pub   4096R/A224060A 2015-07-25 [expires: 2019-07-25]
uid                  openHAB Bintray Repositories <owner@openhab.org>
sub   4096R/98F622D2 2015-07-25 [expires: 2019-07-25]
```

So, what's wrong here ?

**Comment by theoweiss** [comment]
@nRaecheR it should work now. I had to schedule a signing request for the bintray repo.

**Comment by theoweiss** [comment]
@nRaecheR Can you please test it again. You have to call "apt-get update" again.

**Comment by nRaecheR** [comment]
@theoweiss Thank you for the update. I tried it and now it seems that the package signing has worked, but I'm still unable to download the packages. I still get the 403 forbidden errors. Here the output of apt-get dist-upgrade : 

```
Calculating upgrade... Done
The following packages will be upgraded:
   openhab-addon-action-mail (1.7.0 => 1.7.1)
   openhab-addon-binding-zwave (1.7.0 => 1.7.1)
   openhab-runtime (1.7.0 => 1.7.1)
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 37.8 MB/37.9 MB of archives.
After this operation, 6144 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Err http://dl.bintray.com/openhab/apt-repo/ stable/main openhab-runtime all 1.7.1
  403  Forbidden
Err http://dl.bintray.com/openhab/apt-repo/ stable/main openhab-addon-binding-zwave all 1.7.1
  403  Forbidden
E: Failed to fetch http://dl.bintray.com/openhab/apt-repo/pool/main/o/openhab-runtime-1.7.1.deb  403  Forbidden

E: Failed to fetch http://dl.bintray.com/openhab/apt-repo/pool/main/o/openhab-addon-binding-zwave-1.7.1.deb  403  Forbidden

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by theoweiss** [comment]
That's good. Can you please open another issue for the 403 problem. Thanks.

**Comment by jereynolds** [comment]
I'm seeing this issue with an unauthenticated package trying to install version 1.8.3 on Ubuntu 16.04. These install steps have worked successfully for me before (they are being executed by a chef recipe which has run successfully on other machines) but I'm getting errors now.

I installed the key:
`wget -qO 'https://bintray.com/user/downloadSubjectPublicKey?username=openhab | sudo apt-key add -`

And verified it:
```
$ apt-key list
/etc/apt/trusted.gpg
--------------------
[... Ubuntu keys here ...]

pub   4096R/A224060A 2015-07-25 [expires: 2019-07-25]
uid                  openHAB Bintray Repositories <owner@openhab.org>
sub   4096R/98F622D2 2015-07-25 [expires: 2019-07-25]
```

Added the listing:
```
$ echo "deb http://dl.bintray.com/openhab/apt-repo stable main" | sudo tee /etc/apt/sources.list.d/openhab.list
deb http://dl.bintray.com/openhab/apt-repo stable main
$ sudo apt-get update
Ign:1 http://dl.bintray.com/openhab/apt-repo stable InRelease
Hit:2 http://ppa.launchpad.net/longsleep/ubuntu-pine64-flavour-makers/ubuntu xenial InRelease
Hit:3 http://ports.ubuntu.com xenial InRelease
Hit:4 http://ports.ubuntu.com xenial-updates InRelease
Get:5 http://dl.bintray.com/openhab/apt-repo stable Release [6,050 B]
Hit:6 http://ports.ubuntu.com xenial-security InRelease
Get:7 http://dl.bintray.com/openhab/apt-repo stable Release.gpg [821 B]
Hit:8 http://ports.ubuntu.com xenial-backports InRelease
Fetched 6,871 B in 1s (3,499 B/s)
Reading package lists... Done
```

And tried to install:
```
$ sudo apt-get install openhab-runtime
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  openhab-runtime
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 36.9 MB of archives.
After this operation, 41.4 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openhab-runtime
Install these packages without verification? [y/N]
```

**Comment by theoweiss** [comment]
Hmm, 

I just tested it on my Ubuntu 16.04.1 LTS and it worked like expected:
```
root@u16:~# apt-get install openhab-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  openhab-runtime
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 0 B/36.9 MB of archives.
After this operation, 41.4 MB of additional disk space will be used.
Selecting previously unselected package openhab-runtime.
(Reading database ... 60253 files and directories currently installed.)
Preparing to unpack .../openhab-runtime_1.8.3_all.deb ...
Unpacking openhab-runtime (1.8.3) ...
Processing triggers for systemd (229-4ubuntu7) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up openhab-runtime (1.8.3) ...
### NOT starting on installation, please execute the following statements to configure openHAB to start automatically using systemd
 sudo /bin/systemctl daemon-reload
 sudo /bin/systemctl enable openhab.service
### You can start openhab by executing
 sudo /bin/systemctl start openhab.service
```

No clue what's wrong with your setup.
