### ISSUE TITLE
[Tinkerforge] binding: LCD Backlight subdevice wants a different sibid

### ISSUE THREAD

**Issue by tkuehne71** [openhab/openhab#4539]
According to the wiki, if I want to address the backlight subdevice of a LCD20x4 bricklet, I configure under OH in services/tinkerforge.cfg:

> lcdbacklight.uid=<uid>
> lcdbacklight.subId=backlight
> lcdbacklight.type=backlight
 
However this throws an error:

> [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=321, bundle=207/mvn:org.openhab.binding/org.openhab.binding.tinkerforge/1.9.0.b3]: Updating property backlight of configuration org.openhab.tinkerforge caused a problem: "backlight" is an invalid subId: openhab.cfg has to be fixed!

In older versions of the wiki, one was to set the Type to lcd_backlight but that doesn't work either.

**Comment by 9037568** [comment]
What version of OpenHAB? I'm not seeing this in my first tests...

**Comment by 9037568** [comment]
Never mind. Found it. Looks like this only happens in OH2...

**Comment by 9037568** [comment]
The problem is that the list of subdeviceids is empty, so there's nothing to compare against:
>2016-07-15 08:27:35.225 [DEBUG] [e.internal.model.impl.OHTFDeviceImpl] - Looking through the list of subdeviceids... Length = 0

Not sure why the list is empty...

**Comment by 9037568** [comment]
>According to the wiki, if I want to address the backlight subdevice of a LCD20x4 bricklet, I configure under OH2 in services/tinkerforge.cfg:

I've been unable to find any reference to tinkerforge.cfg in the [wiki](https://github.com/openhab/openhab/wiki/Tinkerforge-Binding). 

But I spent a good while searching through the [binding code](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/config/ConfigurationHandler.java), and as far as I can tell, the backlight subid/type has never been supported, in spite of appearing in the wiki.

Care to try out [this new jar](https://drive.google.com/file/d/0B8vYheWfObP9RFBPN1g4SnVLRVk/view?usp=sharing) to see if it resolves the issue?

**Comment by tkuehne71** [comment]
The error about the lcd backlight subid is gone now.

However, the same error now pop up for the barometer bricklet, that has a subdevice to measure the temperature.

This is the error:
> 2016-07-16 14:13:13.370 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=354, bundle=221/file:/usr/share/openhab2/addons/org.openhab.binding.tinkerforge-1.9.0-SNAPSHOT.jar]: Updating property temperature of configuration org.openhab.tinkerforge caused a problem: "temperature" is an invalid subId: openhab.cfg has to be fixed!
        at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.fillupConfig(ConfigurationHandler.java:751)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.createOHTFDeviceConfig(ConfigurationHandler.java:723)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.createConfig(ConfigurationHandler.java:213)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updated(TinkerforgeBinding.java:887)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]

And here's my corresponding config:

> ## Barometer bricklet
> barometer.uid=uid
> barometer.type=bricklet_barometer
> barometer.callbackPeriod=300000
> barometer.threshold=0
> ## Barometer bricklet Temperature subdevice
> temperature.uid=uid
> temperature.type=barometer_temperature
> temperature.subid=temperature

**Comment by tkuehne71** [comment]
After I reactivate my items, the binding throws another set of exceptions. I also saw this with the previous snapshopt that wa distributed with 2.0b3, however, so this is most likely not a result of your change.

The binidng has problems even in 1.8.1 to use named items from the config file in the item definition like so:

>Number TFW_temperature "Temperatur [%.2f °C]" (TFW) {tinkerforge="name=temperature"}
>Number TFW_pressure "Luftdruck [%.1f hPA]" (TFW) {tinkerforge="name=barometer"}

I'll try see what I get when I remove the config and put all the uid definitions and so on in the items.
Here's the errors for your reference:

>2016-07-16 14:19:43.500 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.505 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.505 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.506 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
2016-07-16 14:19:43.506 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.507 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.507 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.508 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.508 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
>2016-07-16 14:19:43.510 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.tinkerforge.internal.TinkerforgeBinding threw an exception:
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getDeviceIdsForDeviceName(TinkerforgeBinding.java:730)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:612)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.bindingChanged(TinkerforgeBinding.java:637)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeGenericBindingProvider.processBindingConfiguration(TinkerforgeGenericBindingProvider.java:104)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]

**Comment by tkuehne71** [comment]
Update: error stays:

the tinkerforge.cfg is now empty, except for the definition of the host.

My openhab.log now says:
>2016-07-16 14:30:55.822 [WARN ] [internal.config.ConfigurationHandler] - Unrecognized deviceType: bricklet_LCD20x4
>2016-07-16 14:30:55.823 [WARN ] [internal.config.ConfigurationHandler] - Unrecognized deviceType: barometer_temperature
>2016-07-16 14:30:55.825 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=338, bundle=221/file:/usr/share/openhab2/addons/org.openhab.bindin$
org.osgi.service.cm.ConfigurationException: temperature : "temperature" is an invalid subId: openhab.cfg has to be fixed!
        at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.fillupConfig(ConfigurationHandler.java:751)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.createOHTFDeviceConfig(ConfigurationHandler.java:723)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.createConfig(ConfigurationHandler.java:213)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updated(TinkerforgeBinding.java:887)[221:org.openhab.binding.tinkerforge:1.9.0.201607160100]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]

So it seems it still didn't like the config for the LCD bricklet as well as the temperature subdevice for the barometer bricklet, It only throws an error for the second one though.

It's confusing that the code still references fixing the config in openhab.cfg, even though it now gets the config from the items:
>String TFW_LCD         "LCD" { tinkerforge="uid=uid"}
 >Switch TFW_LCDBacklight "LCD Hintergrundbeleuchtung" { tinkerforge="uid=uid, subid=backlight"}
 >Number TFW_temperature "Temperatur Garten-WS [%.2f Â°C]" (TFW,TGroup4,TGroup5,TGroup6,TGroup7) {tinkerforge="uid=uid, subid=temperature"}
> Number TFW_pressure "Luftdruck [%.1f hPA]" (TFW) {tinkerforge="uid=uid"}

I hope I'm not making a noob mistake here, since LCD20x4 isn't even configured anywhere, and it's strange that it should still reference that in the error message.

**Comment by 9037568** [comment]
[This jar](https://drive.google.com/file/d/0B8vYheWfObP9eGxlUkZfTVFTUjQ/view?usp=sharing) should resolve the "unrecognized device" lines (which were just me debugging, really). I've since figured out that these, apparently, are simply devices with no subIDs.

Can you start a new ticket for any of the new errors you'd like to see fixed?

Thanks.

**Comment by tkuehne71** [comment]
not sure what the new jar changes.

When I revert the configurations back to the name references, I still get a lot of the exceptions.

The temperature subdevice still throws the exception about the configuration being invalid.

The LCD backlight device does not work (used to work under 1.8.1).

**Comment by 9037568** [comment]
If you can post a debug log with the errors, I can have a look.

**Comment by tkuehne71** [comment]
Starting in debug mode:

> 2016-07-16 22:09:10.688 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=340, bundle=221/file:/usr/share/openhab2/addons/org.openhab.binding.tinkerforge-1.9.0-SNAPSHOT.jar]: Updating property temperature of configuration org.openhab.tinkerforge caused a problem: "temperature" is an invalid subId: openhab.cfg has to be fixed!
> org.osgi.service.cm.ConfigurationException: temperature : "temperature" is an invalid subId: openhab.cfg has to be fixed!
> at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.fillupConfig(ConfigurationHandler.java:751)[221:org.openhab.binding.tinkerforge:1.9.0.201607161619]
> at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.createOHTFDeviceConfig(ConfigurationHandler.java:723)[221:org.openhab.binding.tinkerforge:1.9.0.201607161619]
> at org.openhab.binding.tinkerforge.internal.config.ConfigurationHandler.createConfig(ConfigurationHandler.java:213)[221:org.openhab.binding.tinkerforge:1.9.0.201607161619]
> at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updated(TinkerforgeBinding.java:887)[221:org.openhab.binding.tinkerforge:1.9.0.201607161619]
> at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
> at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
> at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
> at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
> at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
> at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
> at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
> at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
> 2016-07-16 22:09:40.721 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: null
> 2016-07-16 22:09:42.617 [INFO ] [marthome.event.ItemStateChangedEvent] - TFW_LCD changed from TFNUM<313>   0 to TFNUM<00>Temperatur :       C
> 2016-07-16 22:09:42.617 [INFO ] [marthome.event.ItemStateChangedEvent] - TFW_LCD changed from TFNUM<00>Temperatur :       C to TFNUM<10>rel.Feuchte:       %
> 2016-07-16 22:09:42.618 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: null
> 2016-07-16 22:09:42.629 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: null
> 2016-07-16 22:09:42.637 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: backlight
> 2016-07-16 22:09:49.144 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: button0
> 2016-07-16 22:09:49.191 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TFW_LCDBacklight' received command ON
> 2016-07-16 22:09:49.192 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: backlight
> 2016-07-16 22:09:49.193 [INFO ] [marthome.event.ItemStateChangedEvent] - TFW_Button0 changed from OFF to ON
> 2016-07-16 22:09:50.340 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TFW_Button0' received command OFF
> 2016-07-16 22:09:50.340 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: button0
> 2016-07-16 22:09:50.345 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TFW_LCDBacklight' received command OFF
> 2016-07-16 22:09:50.346 [ERROR] [kerforge.internal.TinkerforgeBinding] - COMMAND no tinkerforge device found for command for item uid: vBL subId: backlight
> 2016-07-16 22:09:50.350 [INFO ] [marthome.event.ItemStateChangedEvent] - TFW_Button0 changed from ON to OFF
> 2016-07-16 22:09:50.358 [INFO ] [marthome.event.ItemStateChangedEvent] - TFW_LCDBacklight changed from ON to OFF

Yo can see the startup error for the temperature subdevice and when I send ON events to the backlight, it also returns an error message.

**Comment by theoweiss** [comment]
You don't need any configuration in tinkerforge.cfg for the LCD Backlight. Here is a configuration example for the Tinkerforge weather station: https://github.com/theoweiss/openhab2-tinkerforge-configuration-examples/tree/master/weatherstation

**Comment by tkuehne71** [comment]
yes. my tinkerforge.cfg is empty, except for the hosts definition.

**Comment by theoweiss** [comment]
Could you please post your current configuration and the corresponding logs as attached files (https://github.com/blog/2061-attach-files-to-comments).

Thanks,
Theo

**Comment by tkuehne71** [comment]
Here you go. I've redacted the files a bit to remove config or output not relevant to my tinkerforge stuff.

This is with the debug bundle jar that was posted in this thread. 

[tf.zip](https://github.com/openhab/openhab/files/367575/tf.zip)

**Comment by theoweiss** [comment]
I had a look into the files. Could you please rerun the test using the released tinkerforge binding and not the snapshot and post the log again as attachment.

**Comment by tkuehne71** [comment]
already did. same result.

**Comment by theoweiss** [comment]
Are you sure? The log you posted references the snapshot:

> 2016-07-16 22:09:10.688 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=340, bundle=221/file:/usr/share/openhab2/addons/org.openhab.binding.tinkerforge-1.9.0-SNAPSHOT.jar]: Updating property temperature of configuration org.openhab.tinkerforge caused a problem: "temperature" is an invalid subId: openhab.cfg has to be fixed!

Please search for "temperature" in all your config files, use `grep -Ri *` in the appropriate directories.

**Comment by tkuehne71** [comment]
yes, i know. I reran the config with the budled version, and it produced the same results.

**Comment by tkuehne71** [comment]
I got around to capturing the log from my rerun:

[TFW.pdf](https://github.com/openhab/openhab/files/368903/TFW.pdf)

**Comment by theoweiss** [comment]
According to your log  file there is still a /usr/share/openhab2/addons/org.openhab.binding.tinkerforge-1.9.0-SNAPSHOT.jar you have to remove the jar. 
How did you install openHAB 2: manual or apt installation?

**Comment by theoweiss** [comment]
FYI: I've just setup a test bed with openHAB 2 and the configuration mentioned above (https://github.com/theoweiss/openhab2-tinkerforge-configuration-examples/tree/master/weatherstation). It works pretty well. Could you please double check all your configuration files and openHAB 2 installation.

**Comment by tkuehne71** [comment]
I recreated the problem. I set up a completely new VM with ubuntu server 16.04 LTS, installed Oracle Java 8 and the openhab online bundle from bintray using apt.

When I start the TF binding first with the configs given in the zip file above everything works fine just as you said.
Then I changed the config of the items to refer to the devices by name references and added the appropriate name references to tinkerforge.cfg, getting a lot of exceptions on the next start.

Now, I remove the configuration from tinkerforge.cfg and reset the item definitions to refer to the devices directly by their subids. Although this is now the same sonfiguration that worked just a bit earlier, the log file gets filled withthe same error messages as attached.

Hope you can recreate and investigate.
[tinkerforge_named.txt](https://github.com/openhab/openhab/files/375162/tinkerforge_named.txt)
[tinkerforge_uid_with_error.txt](https://github.com/openhab/openhab/files/375163/tinkerforge_uid_with_error.txt)

**Comment by theoweiss** [comment]
This sounds really weird. I will check if I can reproduce this. Thanks for the debugging.

**Comment by theoweiss** [comment]
Work was pretty crazy the last weeks and now I'm on holidays, I will check this in a couple of weeks.

Thanks for your patience,
Theo
